### ISSUE TITLE
Update Travis CI example to include new 'cache:npm'

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1100]
Travis newly release `cache:npm` should be added to our Travis example. Release notes: https://changelog.travis-ci.com/for-node-js-builds-cache-npm-shortcut-is-available-77295

https://docs.cypress.io/guides/guides/continuous-integration.html#Example-travis-yml-config-file

Replace:
```
cache:
  directories:
    - ~/.npm
    - ~/.cache
```

With:
```
cache: 
  npm: true
  directories:
    - ~/.cache
```
