### ISSUE TITLE
Auto-merge GitHub Action Workflow

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-documentation#2233]
## Objective
Add a GitHub Action workflow to auto-merge `develop` into `master` after successful PRs into the `develop` branch.

## Goal
To optimize the PR deployment workflow by removing the need to manually create PRs from `develop` into `master` if the build is green.

## Implementation
1. A GH action to create a PR from `develop` into `master` after any PR is successfully merged into `develop`. Proposed implementation:

```yaml
name: Create PR: develop -> master

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
    pull-request:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: github.event.pull_request.merged == true
        with:
          github_token: ${{ secrets.GH_TOKEN }}
```

2. A GH action to automatically merge the created PR (^above) into `master`: Proposed implementation:
```yaml
name: Merge PR: develop -> master

on:
  pull_request:
    branches:
      - master

jobs:
  merge-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@v0.3.0
		if: github.event.pull_request.head.ref == 'develop'
        with:
          token: ${{ secrets.GH_TOKEN}}
```

Other requirements:
 - The `develop` branch needs protections that require reviews and successful status checks to stop unsuccessful builds from being auto-merged into master.
 - The `master` branch protections must not require reviews for PRs.
