### ISSUE TITLE
add Azure CI example link

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#922]
- with parallel support

https://docs.microsoft.com/en-us/azure/devops/pipelines/index?view=vsts

**Comment by jhangvar** [comment]
Any plans for this item? We're interested in running parallell CI hosts on Azure Pipelines.

**Comment by michaelw85** [comment]
👍 I would be very interested in a guide especially how to aggregate test results when running in parallel.

**Comment by michaelw85** [comment]
I've done an azure setup today and it ended up being very simple.

I've create a job that runs:
- npm install
- config transform
- run tests
- publish screenshots
- publish videos
- publish test result xml files

To make it run in parallel follow documentation related to [job matrix](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops#multi-configuration). Configure a matrix for the job defining what test files to run and pass this setting into a config transform step setting the "testFiles" entry in the cypress.json. Alternatively you could also just pass the argument to the CLI.

Result aggregation is done automatically by azure if you upload your test results.

**Comment by nacron** [comment]
@michaelw85 How did you do it? I am sitting at the same problem, the test run is no problem but how did you publish the screenshots, videos and test results?
Did you use the --record with the cypress dashboard?

**Comment by michaelw85** [comment]
@nacron I do not use the --record option nor the dashboard. I just use the publish artifacts build step.

Here's part of my cypress azure pipeline template (I'm using Aurelia hence the `au` command):
```yml
  - script: |
      .\node_modules\.bin\au cypress --run
    displayName: Run E2E tests (Cypress)
    workingDirectory: $(Build.SourcesDirectory)

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Screenshots (Cypress)'
    condition: failed()
    inputs:
      artifactName: 'screenshots'
      targetPath: '$(Build.SourcesDirectory)/test/e2e/screenshots'

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Videos (Cypress)'
    condition: failed()
    inputs:
      artifactName: 'videos'
      targetPath: '$(Build.SourcesDirectory)/test/e2e/videos'

  - task: PublishTestResults@2
    displayName: Publish test results (Cypress)
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '$(Build.SourcesDirectory)/test/cypress-junit-report.*.xml'
```

**Comment by jhangvar** [comment]
I understand that you don't use --parallel in your Azure setup, is that correct @michaelw85? If not, how do you distribute the tests between agents in Azure? Is that hardcoded in testFiles?

**Comment by michaelw85** [comment]
@jhangvar Yes I do. I have a job that uses the template I posted before. 
Here's the job that I use:

```yml
parameters:
  pool: E2E
  url: https://yourwebsite.com
  maxParallel: 1
  matrix:
    all:
      suites: '**/*.*'

jobs:
- job: e2e_test
  strategy:
    maxParallel: ${{ parameters.maxParallel }}
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  pool:
    name: ${{ parameters.pool }}
    demands: npm
  steps:
  - template: ../Git/gitversion.yml

  - template: ../NPM/install.yml

  - template: ../Aurelia/cypress.yml
    parameters:
      url: ${{ parameters.url }}
      suites: $(suites)
      sourcePath: $(Build.SourcesDirectory)
```
The `../Aurelia/cypress.yml` refers to the setup I posted before.
The matrix parameters determine what to run so you would replace `all` by multiple test suites and pass in a pattern what tests to run. This unfortunately is not as advanced as the system offered by Cypress which uses a load balancing like setup to dynamically push tests to build servers.

**Comment by jhangvar** [comment]
Thanks for sharing @michaelw85. I'm curious if the --parallel flag is supported in an Azure Devops pipeline setup and how that configuration would look like (how to input ci build id, etc), but I take it you haven't set that up yourself. Anyone else?

**Comment by michaelw85** [comment]
@jhangvar I do not use the parallel flag, I use the azure pipeline to manage parallelism. So my latest post shows the option: 'maxParallel' if you put this to 2 and you have 2 entries in your matrix than 2 machines in the pool you provided will be used to run the tests in parallel. What the matrix does is run your job for each matrix entry and based on the amount set to maxParallel and available machines run in parallel, it will schedule jobs until all entries in your matrix are done.

Params could look something like this:
```yml

- template: e2e-template.yml
parameters:
  pool: E2E
  url: https://yourwebsite.com
  maxParallel: 2
  matrix:
    suite_1:
      suites: 'testFolder/suite_1/*.*'
    suite_2:
      suites: 'testFolder/suite_2/*.*'
```
